# Generated by Django 4.1.6 on 2023-03-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_profile_followingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followerprofile',
            field=models.ManyToManyField(blank=True, related_name='Profile_followers', to='twitter.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followingprofile',
            field=models.ManyToManyField(blank=True, related_name='Profile_following', to='twitter.profile'),
        ),
    ]
