# Generated by Django 4.1.6 on 2023-03-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_profile_followerprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='totalfollowers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='totalfollowing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followerprofile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followingprofile',
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followersprofile', models.ManyToManyField(related_name='profile_followers', to='twitter.profile')),
                ('profileuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.profile')),
            ],
        ),
    ]
