# Generated by Django 4.1.6 on 2023-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_rename_followers_profile_totalfollowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followersprofile',
            field=models.ManyToManyField(blank=True, related_name='profile_followers', to='twitter.profile'),
        ),
    ]
