# Generated by Django 4.1.6 on 2023-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_alter_followers_followersprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='followingprofile',
            field=models.ManyToManyField(blank=True, related_name='profile_following', to='twitter.profile'),
        ),
    ]
