# Generated by Django 4.1.7 on 2023-03-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_followers_followingprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='totalfollowers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='totalfollowing',
        ),
    ]
