# Generated by Django 4.1.7 on 2023-03-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_remove_profile_totalfollowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followersprofile',
            field=models.ManyToManyField(related_name='profile_followers', to='twitter.profile'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='followingprofile',
            field=models.ManyToManyField(related_name='profile_following', to='twitter.profile'),
        ),
    ]
